/**
 * Plugin client barrel — register all installed plugin client entries here.
 *
 * In production this file is generated by scripts/gen-plugin-barrel.ts which
 * globs node_modules/@adept-plugins/* and calls each plugin's registerClient.
 * For now the registrations are manual.
 */

import { clientPluginRegistry } from "./registry";
import { registerClient as registerOpeningShowClient } from "@adept-plugins/opening-show/client";
import { registerClient as registerSpectatorBetClient } from "@adept-plugins/spectator-bet/client";
import { registerClient as registerFuneralClient } from "@adept-plugins/funeral/client";
import { registerClient as registerFinalRoundSelectionClient } from "@adept-plugins/final-round-selection/client";
import { registerClient as registerRaccoonClient } from "@adept-plugins/raccoon/client";
import { registerClient as registerWheelOfAdeptsClient } from "@adept-plugins/wheel-of-adepts/client";

// @adept-plugins/opening-show
registerOpeningShowClient(clientPluginRegistry);

// @adept-plugins/spectator-bet
registerSpectatorBetClient(clientPluginRegistry);

// @adept-plugins/funeral (story_video + donations)
registerFuneralClient(clientPluginRegistry);

// @adept-plugins/final-round-selection
registerFinalRoundSelectionClient(clientPluginRegistry);

// @adept-plugins/raccoon
registerRaccoonClient(clientPluginRegistry);

// @adept-plugins/wheel-of-adepts
registerWheelOfAdeptsClient(clientPluginRegistry);

export { clientPluginRegistry };
