/**
 * Plugin client barrel — register all installed plugin client entries here.
 *
 * In production this file is generated by scripts/gen-plugin-barrel.ts which
 * globs node_modules/@adept-plugins/* and calls each plugin's registerClient.
 * For now the registrations are manual.
 */

import { clientPluginRegistry } from "./registry";
import { registerClient as registerSpectatorPicksClient } from "@adept-plugins/spectator-picks/client";
import {
  StoryVideoSegmentView,
  DonationsSegmentView,
  BetweenFinalSegmentView,
} from "./builtins";

// @adept-plugins/spectator-picks
registerSpectatorPicksClient(clientPluginRegistry);

// Built-in segments
clientPluginRegistry.registerSegmentView("builtin", "story_video", StoryVideoSegmentView);
clientPluginRegistry.registerSegmentView("builtin", "donations", DonationsSegmentView);
clientPluginRegistry.registerSegmentView("builtin", "between_final", BetweenFinalSegmentView);

export { clientPluginRegistry };
